import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { afterEach, expect, it, vi } from 'vitest'
import { FtthDocumentationPage } from './FtthDocumentationPage.jsx'
import { dashboardApi } from '../../api/dashboard.js'
vi.mock('../../api/dashboard.js', () => ({ dashboardApi: { listDocumentation: vi.fn() } }))
afterEach(() => { cleanup(); vi.clearAllMocks() })
it('pages the screen preview while retaining all sheets and image readiness for print', async () => {
  dashboardApi.listDocumentation.mockResolvedValue({ data: { source: 'ftth', items: ['a', 'b'].map(id => ({ id, projectId: 'p', clusterId: id, processId: 'j', projectName: 'Project', clusterName: id, processName: 'Pekerjaan', originalName: `${id}.png`, mimeType: 'image/png', downloadUrl: `/api/attachments/${id}` })), options: { projects: [], clusters: [], processes: [] } } })
  const { container } = render(<FtthDocumentationPage />)
  const photoA = await screen.findByAltText('a.png')
  const photoB = screen.getByAltText('b.png')
  const sheets = container.querySelectorAll('.documentation-sheet')
  expect(sheets).toHaveLength(2)
  expect(sheets[1]).toHaveClass('is-preview-hidden')
  fireEvent.click(screen.getByRole('button', { name: 'Halaman berikutnya' }))
  expect(sheets[0]).toHaveClass('is-preview-hidden')
  expect(sheets[1]).not.toHaveClass('is-preview-hidden')
  expect(screen.getByRole('button', { name: 'Halaman berikutnya' })).toBeDisabled()
  fireEvent.load(photoB)
  expect(screen.getByText('Cetak / Simpan PDF')).toBeDisabled()
  fireEvent.load(photoA)
  expect(screen.getByText('Cetak / Simpan PDF')).toBeEnabled()
})
it('filters project/cluster and prints only after image loading, with PDF as a link', async () => {
  const base = { reportId: 'r1', projectId: 'p1', clusterId: 'c1', processId: 'j1', projectName: 'Project A', clusterName: 'Cluster A', processName: 'Sitac', downloadUrl: '/api/ftth/reports/r1/attachments/a/download' }
  dashboardApi.listDocumentation.mockResolvedValue({ data: { source: 'ftth', items: [{ ...base, id: 'a', originalName: 'foto.png', mimeType: 'image/png' }, { ...base, id: 'b', originalName: 'izin.pdf', mimeType: 'application/pdf' }], options: { projects: [{ id: 'p1', name: 'Project A' }], clusters: [{ id: 'c1', name: 'Cluster A', projectId: 'p1' }], processes: [{ id: 'j1', name: 'Sitac' }] } } })
  render(<FtthDocumentationPage />)
  const photo = await screen.findByAltText('foto.png')
  expect(photo).toHaveAttribute('crossorigin', 'use-credentials')
  expect(screen.getByText('Cetak / Simpan PDF')).toBeDisabled()
  expect(screen.getByText('Dokumen: izin.pdf')).toBeInTheDocument()
  fireEvent.load(photo)
  expect(screen.getByText('Cetak / Simpan PDF')).toBeEnabled()
  fireEvent.click(screen.getByRole('button', { name: 'Tampilan folder' }))
  expect(screen.getByRole('region', { name: 'Folder dokumentasi' })).toBeInTheDocument()
  expect(screen.queryByText('Cetak / Simpan PDF')).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button', { name: 'Tampilan PDF' }))
  expect(screen.getByText('Cetak / Simpan PDF')).toBeDisabled()
  fireEvent.load(screen.getByAltText('foto.png'))
  fireEvent.change(screen.getByLabelText('Project'), { target: { value: 'p1' } })
  fireEvent.change(screen.getByLabelText('Cluster'), { target: { value: 'c1' } })
  fireEvent.click(screen.getByText('Tampilkan'))
  await waitFor(() => expect(dashboardApi.listDocumentation).toHaveBeenCalledWith({ projectId: 'p1', clusterId: 'c1', pekerjaanId: '' }))
})
